### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-526-SU24/hw-03-rahathelal#1]
Dear @rahathelal -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

**93.5/100**
---

### Exercise 1: `[19 / 20 points]`
- Plot reproduction: `[19 / 20]`
- **Feedback**: The plot is close enough (the colors are off, but I'm not strict on this due to individual sensitivity to colors). The annotations and title are cut-off however, which could have been fixed by tweaking the coordinates. 

### Exercise 2: `[15 / 15 points]`

  - Result narrative 1: `[5 / 5]`
  - Result narrative 2: `[5 / 5]`
  - Result narrative 3: `[5 / 5]`
  - Feedback: [Insert feedback here.]

### Exercise 3: `[17.5 / 20 points]`

  - Data wrangling & relabeling: `[4 / 5]`
  - Data frame recreation: `[5 / 5]`
  - Plot reproduction: `[3.5 / 5]`
  - `facet_grid` step: `[5 / 5]` 
  - Feedback: There are a few issues:
1. Your strip titles are cut-off, likely due to your plot fitting too small of dimensions
2. You needed to remove the y-axis title and use the correct x-axis title:
```
labs(
      x = "Mean Likert score \n(Error bars range from 10th to 90th percentile)",
      y = NULL
    ) +
```
3. You needed to remove gridlines within the plot. Here's the theme steps I took:
```
theme(
      panel.grid = element_blank(),
      strip.background = element_rect(fill = "gray90", linewidth = 0.25),
      strip.text.y = element_text(angle = 0, size = 9),
      strip.text.x = element_text(size = 8.4),
      axis.text = element_text(size = 8.4),
      axis.title = element_text(size = 12)
    )
```
  
4. Additionally, your approach is close, but your relabeling isn't quite where it needs to be. Here's the rubric version:
```
covid_survey <- covid_survey |>
  mutate(
    exp_already_vax = case_when(
      exp_already_vax == 0 ~ "No",
      exp_already_vax == 1 ~ "Yes"
    ),
    exp_flu_vax = case_when(
      exp_flu_vax == 0 ~ "No",
      exp_flu_vax == 1 ~ "Yes"
    ),
    exp_profession = case_when(
      exp_profession == 0 ~ "Medical",
      exp_profession == 1 ~ "Nursing"
    ),
    exp_gender = case_when(
      exp_gender == 0 ~ "Male",
      exp_gender == 1 ~ "Female",
      exp_gender == 3 ~ "Non-binary third gender",
      exp_gender == 4 ~ "Prefer not to say"
    ),
    exp_race = case_when(
      exp_race == 1 ~ "American Indian / Alaskan Native",
      exp_race == 2 ~ "Asian",
      exp_race == 3 ~ "Black / African American",
      exp_race == 4 ~ "Native Hawaiian / Other Pacific Islander",
      exp_race == 5 ~ "White",
    ),
    exp_ethnicity = case_when(
      exp_ethnicity == 1 ~ "Hispanic / Latino",
      exp_ethnicity == 2 ~ "Non-Hispanic/Non-Latino"
    ),
    exp_age_bin = case_when(
      exp_age_bin == 0 ~ "<20",
      exp_age_bin == 20 ~ "21-25",
      exp_age_bin == 25 ~ "26-30",
      exp_age_bin == 30 ~ ">30",
    )
  )
```
 and

```
mutate(
    explanatory = fct_relevel(explanatory, c("All", "Age", "Gender", "Race", "Ethnicity", "Profession")),
    explanatory_value = fct_relevel(explanatory_value, c("<20", "21-25", "26-30", ">30"))
  )
```
 
### Exercise 4: `[9 / 10 points]`

- New plot: `[4 / 5 points]`
- Narrative: `[5 / 5 points]`
- Feedback: Your approach is close, but your relabeling isn't quite where it needs to be along with some other styling (see above feedback as well).

### Exercise 5: `[13 / 15 points]`
- Bar plots: `[8 / 10]`
- Narrative: `[5 / 5]`
Feedback: Your plots were squished, which could have been fixed by making the legend at the top, and using `nrow = 2` instead of `ncol = 2`. 

Feedback: [Insert feedback here.]

### Overall: `[20 / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[3 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by rahathelal** [comment]
Dear @Gchism94, thanks for your feedback, please find the explanation here:

- For Question 3, I had first created a basic plot and also mentioned in the answer that the basic one will have minimal features compared to the expected original plot from Question 2. I had then tried to improvise on this basic plot and make it similar to the original plot as displayed in the immediate section. However, I understand that I should not have included two different plots (a basic and then a refined one) because that created confusion. So, I will rectify the errors as suggested by you and render the plot again in HW-04 question 1. 
- For Questions 4 and 5, I will have the changes implemented and push the modified code again.

Thanks,
